name: Get WIP List
on:
  push:

jobs:
  Get:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Join above.md, wip.md, and below.md
        run: |
          cat ./files/above.md ./files/wip.md ./files/below.md > readme.md

      - name: Setup git config
        run: |
          git config user.name "SporkelBot"
          git config user.email "98554370+SporkelBot@users.noreply.github.com"
          
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated"
          git push
