name: Get WIP List
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  Get:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Get WIP list
        run: |
          curl -X GET 'https://raw.githubusercontent.com/LegoManiac04/wip-list/main/wip.md' -o ./list.md

      - name: Join above.md, list.md, and below.md
        run: |
          cat ./files/above.md list.md ./files/below.md > test.md

      - name: Cleanup
        run: |
          rm list.md

      - name: Setup git config
        run: |
          git config user.name "SporkelBot"
          git config user.email "98554370+SporkelBot@users.noreply.github.com"
          
      - name: Commit
        run: |
          # Stage the file, commit and push
          git add .
          git diff-index --quiet HEAD || git commit -m "Updated"
          git push
